[package]
name = "rust_lab"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
lazy_static = "1.4.0"
lalrpop-util = { version = "0.22.1", features = ["lexer", "unicode"] }
regex = "1"